name: Node.js CI/CD

on:
  push:
    branches: [main]  # đổi thành 'main' nếu repo của bạn dùng main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy code từ GitHub
        uses: actions/checkout@v4

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cài đặt thư viện
        run: npm install

